name: CI

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./${{ inputs.package }}
    steps:
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  typecheck:
    name: Type-check
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - run: yarn typecheck
  # test_affected:
  #   name: Run tests for affected files
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref != 'refs/heads/master'}}
  #   needs: [setup-deps]
  #   strategy:
  #     matrix:
  #       package: [admin, shared, user]
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: re-use cache
  #       uses: ./.github/actions/cache
  #     - name: Fetch base branch
  #       id: fetch_base
  #       run: node ./.github/scripts/fetchPrBase ${{ github.token }} ${{ github.sha }}
  #     - name: Run tests
  #       run: lerna run --scope "@virtuslab/nfs-${{ matrix.package }}" --stream test:ci -- --changedSince origin/${{ steps.fetch_base.outputs.BASE_BRANCH }}
  # test_all:
  #   name: Run all tests
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/master'}}
  #   needs: [setup-deps]
  #   strategy:
  #     matrix:
  #       package: [admin, shared, user]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: re-use cache
  #       uses: ./.github/actions/cache
  #     - name: Run tests
  #       run: lerna run --scope "@virtuslab/nfs-${{ matrix.package }}" --stream test:ci
