name: CI

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  typecheck:
    name: Type-check
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
        shell: bash
      - run: yarn workspace ${{ inputs.package }} typecheck
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: [setup-deps]
    strategy:
      matrix:
        package: [admin, shared, user]
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
        shell: bash
      - name: Run tests
        run: yarn workspace ${{ inputs.package }} typecheck test:ci
