name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to heroku
        run: git push heroku deploy:master
