name: Deployment

on:
  push:
    branches:
      - deploy

jobs:
  setup-deps:
    name: Setup project dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup cache
        uses: ./.github/actions/cache
  configure:
    name: Configure things
    runs-on: ubuntu-latest
    needs: [setup-deps]
    steps:
      - uses: actions/checkout@v2
      - name: re-use cache
        uses: ./.github/actions/cache
      - name: build apps
        run: yarn workspace foreach run build
      - name: move frontend to static backend files
        run: |
          mkdir ./pantryy_backend/dist/static &&
          cp ./pantryy_frontend/public/index.html ./pantryy_backend/dist/static/index.html
          cp -r ./pantryy_frontend/public/static/. ./pantryy_backend/dist/static/
